export const environment = {
  SUPABASE_URL: import.meta.env.VITE_PUBLIC_SUPABASE_URL,
  SUPABASE_KEY: import.meta.env.VITE_PUBLIC_SUPABASE_ANON_KEY,
  GOOGLE_CLIENT_ID: import.meta.env
    .VITE_SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: import.meta.env
    .VITE_SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET,
};
